### ISSUE TITLE
A question about reference

### ISSUE THREAD

**Issue by weiweiweidong** [aganders3/blog#5]
Hello, I am a student and am learning your code.
I noticed that your 
```
aganders3.github.io/content
/notebooks/Total Variation Reconstruction.ipynb
``` 
cites "**BU - see Afonso 2009 section III-C-4**" for the fact that the Fourier transform and downsampling can be combined into a single matrix A. But I searched around and didn't find a corresponding reference. Can you give me more detailes about the reference?

Thank you for your help.

**Comment by aganders3** [comment]
Thanks for reading. This is the reference:
https://arxiv.org/pdf/0912.3481.pdf

Unfortunately I don't remember this material that well but I can try to answer if you have other questions.

**Comment by weiweiweidong** [comment]
Thank you very much for your help!
 This is so helpful!
Wish you have a good day!
